const AVAILABLE_COMPONENTS_LIST_URL = 'https://api.github.com/repos/$1/$2/contents/$3?ref=$4';
const GITHUB_BRANCH = 'develop';
const GITHUB_COMPONENTS_FOLDER = 'src/app/components';
const GITHUB_DIST_FOLDER = 'dist';
const GITHUB_DOWNLOAD_DIST_URL = 'https://gitpkg.vercel.app/$1/$2/$3/$4?$5';
const GITHUB_REPOSITORY = 'design-system-angular-core';
const GITHUB_USERNAME = 'Eduk29';

module.exports = {
  AVAILABLE_COMPONENTS_LIST_URL: AVAILABLE_COMPONENTS_LIST_URL,
  GITHUB_BRANCH: GITHUB_BRANCH,
  GITHUB_COMPONENTS_FOLDER: GITHUB_COMPONENTS_FOLDER,
  GITHUB_DIST_FOLDER: GITHUB_DIST_FOLDER,
  GITHUB_DOWNLOAD_DIST_URL: GITHUB_DOWNLOAD_DIST_URL,
  GITHUB_REPOSITORY: GITHUB_REPOSITORY,
  GITHUB_USERNAME: GITHUB_USERNAME,
};
